### ISSUE TITLE
Which version of react-leaflet is this based on?

### ISSUE THREAD

**Issue by stroborobo** [MangelMaxime/Fable.ReactLeaflet#1]
Hello Maxime,

can I see anywhere if this is for react-leaflet 1 or 2? Can't seem to find it.

**Comment by MangelMaxime** [comment]
This is for react-leaflet 2.

If you need to use react-leaflet 1, you should be able to use version `0.2.0` of this library.

**Comment by stroborobo** [comment]
Alright, thanks a lot!
